export const data=[
    {
        title:'Apple',
        imageUrl:'https://post.healthline.com/wp-content/uploads/2020/09/Do_Apples_Affect_Diabetes_and_Blood_Sugar_Levels-732x549-thumbnail-1-732x549.jpg'
    },
    {
        title:'Blueberry',
        imageUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNkX9PwImXVpsUnEu69_BZRVNYgUhpQJ6nLw&usqp=CAU'
    },
    {
        title:'Cherry',
        imageUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMS9w-BMX5br8CHuVMqjO5Rr9WbMqPCAExbA&usqp=CAU'
    },
    {
        title:'Corn',
        imageUrl:'https://i0.wp.com/post.healthline.com/wp-content/uploads/2021/03/corn-cob-field-1296x728-header.jpg?w=1155&h=1528'
    },
    {
        title:'Grape',
        imageUrl:'https://minnetonkaorchards.com/wp-content/uploads/2022/04/White-Green-Grapes-SS-1102331153.jpg'
    },
    {
        title:'Orange',
        imageUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCZIcc3BogbCvOiUuiyZWQptOYzqtZUvIrbg&usqp=CAU'
    },
    {
        title:'Peach',
        imageUrl:'https://cdn.shopify.com/s/files/1/2045/8185/products/redhaven-peach2_300x300.jpg?v=1642175876'
    },
    {
        title:'Bell pepper',
        imageUrl:'https://www.almanac.com/sites/default/files/styles/large/public/image_nodes/bell_peppers_dleonis_gettyimages.jpg?itok=Z6m3cDpS'
    },
    {
        title:'Potato',
        imageUrl:'https://www.thespruce.com/thmb/6k5-ACTx6OXqmO--k23ddujl9T4=/5750x0/filters:no_upscale():max_bytes(150000):strip_icc()/how-to-harvest-potatoes-2540062-03-6ef71ddbaa974a2583d7ddf8d74f7c1e.jpg'
    },
    {
        title:'Raspberry',
        imageUrl:'https://www.gardeningknowhow.com/wp-content/uploads/2021/07/ripening-raspberries.jpg'
    },
    {
        title:'Soybean',
        imageUrl:'https://d2jx2rerrg6sh3.cloudfront.net/images/news/ImageForNews_745986_16823072833517897.jpg'
    },
    {
        title:'Squash',
        imageUrl:'https://hips.hearstapps.com/hmg-prod/images/is-squash-a-fruit-squash-1561591075.jpg'
    },
    {
        title:'Strawberry',
        imageUrl:'https://m.media-amazon.com/images/I/71VEOI6MYGL.jpg'
    },
    {
        title:'Tomato',
        imageUrl:'https://media.istockphoto.com/id/187110938/photo/garden-tomatoes.jpg?s=612x612&w=0&k=20&c=b1K8Tifv9HqZ3JDnkF3H--yT5wv7NhV2LfTkQGk5RcI='
    },
]